(lang dune 2.9)
(name ogit)
(package
 (name ogit)
 (synopsis "Projet de programmation fonctionnelle Valrose 2022")
 (description "Projet de programmation fonctionnelle Valrose 2022")
)
(generate_opam_files true)